### ISSUE TITLE
Create beat to ship Cassandra DB health to ES

### ISSUE THREAD

**Issue by towens-goomzee** [Goomzee/cassandrabeat#1]
Please create a beat that ships Cassandra health stats to Elastic Search for visualization. Data sent from the beat should be delivered in the format below:

~~~
{
    "beat": {
        "name": "cassandrabeat",
        "host": "localhost"
    },
    "@timestamp": "YYYY-MM-DDTHH:MM:SS.milliZ",
    "@version": "1",
    "type": "stats",
    "count": 1,
    "table_name": "someval", 
    "write_latency": 0, 
    "read_latency": 0
}
~~~

**Comment by bklise-goomzee** [comment]
format: YYYY-MM-DDTHH:MM:SS.milliZ

**Comment by mikesparr** [comment]
Please don't have capitals for field names. Best practice is lowercase (i.e. Timestamp). I'm unsure if other beats are doing that but let's stick with lowercase.

**Comment by mikesparr** [comment]
Also please note that an ES mapping object is not the same as the object that will be sent to ES. If we reference mappings, then dev needs to know the schema it describes (below). Only the fields within the `properties` would be required within the JSON produced by the beat. In this case:

~~~
{
    "table_name": "someval", 
    "timestamp": "YYYY-MM-DDTHH:MM:SS.milliZ", 
    "write_latency": 0, 
    "read_latency": 0
}
~~~

That mapping is missing the other fields, however, so check other beats mappings. Expected would include `beat`, `beat.name`, `beat.hostname`, `count` which may be produced by libbeat, however our integration test should test the expected object sent to Logstash which will include all those fields.

I'd expect the integration test to confirm an object published like the following (noting that other beats use `@timestamp` for timestamp field name so we should be consistent:

~~~
{
    "beat": {
        "name": "cassandrabeat",
        "host": "localhost"
    },
    "@timestamp": "YYYY-MM-DDTHH:MM:SS.milliZ", 
    "count": 1,
    "table_name": "someval", 
    "write_latency": 0, 
    "read_latency": 0
}
~~~

**Comment by towens-goomzee** [comment]
Per @mikesparr 's recommendations above I have edited the original ticket to display the formatting in which the beat should ship the data
